Initial implementation
projectsyn/component-syn-kube-prometheus pull request #1
Opened 2021-12-30 12:30 UTC by anothertobi

## Checklist

- [x] PR contains a single logical change (to build a better changelog).
- [x] Update the documentation.
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.

2021-12-30 12:49 UTC, anothertobi commented
Not sure how the golden tests work and what isn't ok in the jsonnet lint:
```
make: *** [Makefile:23: lint_jsonnet] Error 2
```
Isn't that useful.

Other than that, I think this PR is ready for a review :)

2022-01-03 16:37 UTC, mhutter commented
```sh
jsonnetfmt --in-place --pad-arrays -- */*.jsonnet
```

needed to be done.

2022-01-05 23:44 UTC, anothertobi commented on class/defaults.yml
> +      params: {}
Should we use `params` or `parameters` to pass values as parameters to kube-prometheus?

2022-01-06 06:15 UTC, mhutter commented on class/defaults.yml
> +      params: {}
Or `spec` since that's the section those parameters will go to?

What are they called in kube-prometheus?

2022-01-06 07:26 UTC, anothertobi commented on class/defaults.yml
> +      params: {}
In kube-prometheus they are called `params`: https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/prometheus.libsonnet#L56

It's not the spec of a resource, but a pass-through of params to kube-prometheus.

2022-01-06 09:00 UTC, mhutter commented on class/defaults.yml
> +      params: {}
Then `params` is appropriate IMO

2022-01-06 09:14 UTC, mhutter requested changes

2022-01-06 09:14 UTC, mhutter commented on docs/modules/ROOT/pages/references/parameters.adoc
> +kubernetes_version: '$dynamic_facts:kubernetesVersion:major}.$dynamic_factskubernetesVersion:minor}'
```suggestion
kubernetes_version: '${dynamic_facts:kubernetesVersion:major}.${dynamic_factskubernetesVersion:minor}'
```

2022-01-06 09:14 UTC, mhutter commented on docs/modules/ROOT/pages/references/parameters.adoc
> +prometheus.params:
Not sure whether this would work like this, I think the examples should be copy-pastable

2022-01-06 09:17 UTC, simu requested changes
### High-level potential gotchas for users

* Currently, there's no protection against having multiple instances which fight over who gets to manage the CRD objects.
* It looks like cluster-scoped objects (clusterroles, etc.) are also created with static names for multiple different instances on the same cluster, unless users explicitly set `parameters.<component>.params.name` to unique values for each instance.

### Other suggestions

All the component files do pretty much exactly the same, I think they could probably be refactored to reduce the amount of copy-pasting necessary to introduce new features. See the inline suggestion.

From a design perspective, it's not clear to me whether multi-instance is the right approach for this component, or if we should rather provide users the possibility to create multiple Prometheus/Alertmanager/Grafana/Blackbox Exporter/... instances through the hierarchy which are all managed by a single instance of the component. This could look something like

```yaml
parameters:
  kube_prometheus:
    prometheus:
      my-awesome-prometheus:
        params: { ... }
      another-super-cool-prometheus:
        params: { ... }
```

and in Jsonnet: 

```jsonnet
local kp =
  (import 'kube-prometheus/main.libsonnet') {
    values+:: {
      common+: {
        namespace: params.namespace,
      },
    },
  };

local proms = [
  kp { 
    prometheus+: com.makeMergeable(params.prometheus[name]) {
      name: name,
    }, 
  }
  for name in std.objectFields(params.prometheus)
];

{
  ['20_prometheus-' + prom]: [
    proms[prom].prometheus[name],
    for name std.objectFields(proms[prom].prometheus)
  ]
  for prom in std.objectFields(proms)
}
```

2022-01-06 09:17 UTC, simu commented on component/prometheus-operator.jsonnet
> +{ '10_prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule }
Why do you even do this? Isn't this exactly the same as just having

```suggestion
{
  ['10_prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.objectFields(kp.prometheusOperator)
}
```

2022-01-06 09:17 UTC, simu commented on component/main.jsonnet
> +local kube_state_metrics = import 'kube-state-metrics.jsonnet';
Refactoring suggestion:

Refactor the code which is mostly exactly the same in each `<component>.jsonnet` a `common.libsonnet` (or something) as follows:

```jsonnet
local kap = import 'lib/kapitan.libjsonnet';
local inv = kap.inventory();
local com = import 'lib/commodore.libjsonnet';
// The hiera parameters for the component
local params = inv.parameters.kube_prometheus;

// map from component parameters key to kube-prometheus key
local componentMap = {
  alertmanager: 'alertmanager',
  blackbox_exporter: 'blackboxExporter',
  grafana: 'grafana',
  kubernetes_control_plane: 'kubernetesControlPlane',
  kube_state_metrics: 'kubeStateMetrics',
  node_exporter: 'nodeExporter',
  prometheus: 'prometheus',
  prometheus_adapter: 'prometheusAdapter',
  prometheus_operator: 'prometheusOperator',
};

local render_component(component, prefix) =
  local kpkey = componentMap[component];
  local kp =
    (import 'kube-prometheus/main.libsonnet') {
      values+:: {
        common+: {
          namespace: params.namespace,
        },
      },

      [kpkey]+: com.makeMergeable(params[component]params),
    };

  {
    ['%s_%s_%s' % (prefix, component, name)]: kp[kpkey][name]
    for name in std.objectFields(kp[kpkey])
  };

{
  render_component: render_component,
}
```

And then you can ditch all the component.jsonnet files and simply have the following:

```suggestion
local common = import 'common.libsonnet';
local prometheus_operator = common.render_component('prometheus_operator', 10);
local prometheus = common.render_component('prometheus', 20);
local alertmanager = common.render_component('alertmanager', 30);
local grafana = common.render_component('grafana', 40);
local node_exporter = common.render_component('node_exporter', 50);
local blackbox_exporter = common.render_component('blackbox_exporter', 60);
local kubernetes_control_plane = common.render_component('kubernetes_control_plane', 70);
local prometheus_adapter = common.render_component('prometheus_adapter', 80);
local kube_state_metrics = common.render_component('kube_state_metrics', 90);
```

2022-01-06 09:17 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Parameters to be passed down to the kube-prometheus component.
It would be nice to get a bit more information here, for example, where I can find what keys I can pass to each component.

Additionally, I'd explicitly inform users here about the current gotchas when using multi-instance, namely, that they need to ensure that they don't install multiple `prometheus-operator` instances (to avoid fights over who gets to manage the CRDs), and to ensure that all instances which instantiate the same kube-prometheus component set a unique name with `<kube-prometheus-component>.params.name`.

2022-01-06 09:18 UTC, anothertobi commented on docs/modules/ROOT/pages/references/parameters.adoc
> +prometheus.params:
Now it should be copy-/pasteable :)

2022-01-06 09:23 UTC, mhutter commented on class/defaults.yml
> +      source: https://github.com/projectsyn/component-kube-prometheus
They come from the necessity to find out how $thing was deployed to a cluster, or which repo an AlertRule must be tuned in etc...

2022-01-06 09:24 UTC, mhutter commented on Makefile.vars.mk
> +endif
Good point, I thought I changed this already in `modulesync-control`

2022-01-06 09:24 UTC, simu commented on class/defaults.yml
> +      source: https://github.com/projectsyn/component-kube-prometheus
Yeah, they don't really help with that, if they're never used in the code...

2022-01-06 09:27 UTC, mhutter commented on component/prometheus-operator.jsonnet
> +{ '10_prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule }
This is copy/pasta from upstream: https://github.com/prometheus-operator/kube-prometheus#compiling

The comment there says:

>serviceMonitor and prometheusRule are separated so that they can be created after the CRDs are ready

2022-01-06 09:34 UTC, simu commented on component/prometheus-operator.jsonnet
> +{ '10_prometheus-operator-prometheusRule': kp.prometheusOperator.prometheusRule }
Doesn't matter since we deploy everything with ArgoCD, which is smart enough to create CRDs first when they're part of the same application.

2022-01-13 13:56 UTC, mhutter commented
> From a design perspective, it's not clear to me whether multi-instance is the right approach for this component, or if we should rather provide users the possibility to create multiple Prometheus/Alertmanager/Grafana/Blackbox Exporter/... instances through the hierarchy which are all managed by a single instance of the component. This could look something like

@anothertobi WDYT? Having a single component instance that manages multiple Prometheus/... instances would

a. probably perform better
b. allow us to verify things like making sure there's only a single `prometheus-operator` instance

2022-01-17 13:05 UTC, anothertobi commented
@mhutter 

> a. probably perform better

Performance is mainly related to how many kube-prometheus components effectively have to be rendered. For this, it's irrelevant whether this component is single- or multi-instance.

>  b. allow us to verify things like making sure there's only a single prometheus-operator instance

We could only ensure that it's not possible to create multiple `prometheus-operator` instances with this component when used in the whole Syn lifecycle. I'd make it the responsibility of the user to only deploy one `prometheus-operator`.

However, I do agree that the component should be single-instance considering that the full Syn stack is intended for cluster-infrastructure and not application infrastructure. -> If a user wants a Prometheus for their application, they could use this component in a GitLab pipeline, but not as part of the "Syn stack".

2022-01-17 13:23 UTC, anothertobi commented on component/alertmanager.jsonnet
> +      common+: {
For this we have to stick with the multi instance approach.

2022-01-17 15:43 UTC, TheBigLee commented
> Not sure how the golden tests work and what isn't ok in the jsonnet lint:
> 
> ```
> make: *** [Makefile:23: lint_jsonnet] Error 2
> ```
> 
> Isn't that useful.
> 
> @mhutter do you know what needs to be done?
> 
> Other than that, I think this PR is ready for a review :)

This should not be a problem anymore. Anyways. this can be solved by running `make format`

2022-01-17 16:36 UTC, simu commented on component/alertmanager.jsonnet
> +      common+: {
Yeah, that should work, with the restriction that you now can't have an instance of the component which is called `common` since that name is used as a "magic" key for configurations which apply to all instances of the component, unless you further subdivide each `params[component]` into `common` and `instances`. I'd suggest also having a global `params.common` which is used as the baseline for all components, like this:

```jsonnet
values+:: {
  common+: {
    namespace: params.namespace,
  } + com.makeMergeable(params.common) + com.makeMergeable(params[component].common),
}
```

2022-01-18 12:11 UTC, TheBigLee commented on component/alertmanager.jsonnet
> +      common+: {
Ok thanks. Implemented it this way and also documented the parameters

2022-03-29 15:42 UTC, TheBigLee commented on Makefile.vars.mk
> +COMMODORE_CMD  ?= $(DOCKER_CMD) $(DOCKER_ARGS) --security-opt label=disable $(root_volume) docker.io/projectsyn/commodore:latest component compile . $(commodore_args)
> From a design perspective, it's not clear to me whether multi-instance is the right approach for this component, or if we should rather provide users the possibility to create multiple Prometheus/Alertmanager/Grafana/Blackbox Exporter/... instances through the hierarchy which are all managed by a single instance of the component. This could look something like

We opted to go with the multi_instance variant to leverage hierarchical setups to avoid duplicating settings.

> It looks like cluster-scoped objects (clusterroles, etc.) are also created with static names for multiple different instances on the same cluster, unless users explicitly set parameters.<component>.params.name to unique values for each instance.

This has been fixed

2022-03-30 11:39 UTC, tobru commented
All components are named `component-$name`. This one should be named accordingly. Suggestion: `component-syn-kube-prometheus`

2022-05-12 09:46 UTC, bastjan commented on docs/modules/ROOT/pages/references/parameters.adoc
> +kubernetes_version: '${dynamic_facts:kubernetesVersion:major}.${dynamic_factskubernetesVersion:minor}'
```suggestion
kubernetes_version: '${dynamic_facts:kubernetesVersion:major}.${dynamic_facts:kubernetesVersion:minor}'
```

2022-05-13 12:21 UTC, bastjan commented on component/common.libsonnet
> +local global = inv.parameters.global;
I've added the `com.getValueOrDefault` as a stop-gap so the component compiles again. Not happy with it though.

2022-05-13 13:05 UTC, simu commented on component/common.libsonnet
> +local global = inv.parameters.global;
An alternative would be to introduce a component parameter which allows overriding container registries.

2022-05-17 08:40 UTC, bastjan commented on component/common.libsonnet
> +        [kpkey]+: {name: std.asciiLower(kpkey + '-' + instance) } + com.makeMergeable(params[component].config),
This has been solved.

2022-05-18 17:38 UTC, bastjan commented
@simu Could you please take another look? 😊

I'd like to merge this more or less as it is now and work on the next issues (authentication, rename, new template) in separate PRs.

2022-05-18 17:41 UTC, bastjan commented on component/common.libsonnet
> +local global = inv.parameters.global;
I now see where the `global:` is coming from

2022-05-19 07:42 UTC, simu approved these changes
Logic LGTM. Personally I'd use some more vertical space for some of the Jsonnet, in particular for the folds as I find that makes the code somewhat more readable, but no hard feelings either way.

In a follow-up, we should make sure that the addons provided by the component are documented, especially why one might want to use them.

Finally, I'd suggest running modulesync for this component after merging this PR, since I'm not sure `.sync.yml` and the various managed files are currently in sync.

2022-05-19 07:42 UTC, simu commented on .sync.yml
> +  githubUrl: https://github.com/projectsyn/component-kube-prometheus
```suggestion
  componentName: syn-kube-prometheus
```

2022-05-19 07:42 UTC, simu commented on class/defaults.yml
> +    kubernetes_version: 1.21
I'm pretty sure something somewhere would be very unhappy to see `kubernetes_version` as a float.

```suggestion
    kubernetes_version: '1.21'
```

2022-05-19 07:42 UTC, simu commented on component/addons/nodeexporter-remove-mountpropagation.libsonnet
> +// This addons removes the mountPropagation field from the node-exporter host mounts.
```suggestion
// This addon removes the mountPropagation field from the node-exporter host mounts.
```

Would be nice to get an explanation why this addon may be necessary.

2022-05-19 07:42 UTC, simu commented on component/addons/remove-securitycontext.libsonnet
> +// This addons removes the securityContext keys from the stack. Used on openshift.
```suggestion
// This addon removes the securityContext keys from the stack. Used on OpenShift.
```

2022-05-19 07:42 UTC, simu commented on component/common.libsonnet
> +});
This needs cleanup in a follow-up.

2022-05-19 07:42 UTC, simu commented on component/operator.libsonnet
> +// main template for kube_prometheus
If we have file comments, they should be correct ;)

```suggestion
// template for prometheus-operator
```

2022-05-19 07:42 UTC, simu commented on .sync.yml
> +  title: kube-prometheus
```suggestion
  name: syn-kube-prometheus
  title: syn-kube-prometheus
```

2022-05-19 07:42 UTC, simu commented on docs/antora.yml
> +title: kube-prometheus
```suggestion
name: syn-kube-prometheus
title: syn-kube-prometheus
```

2022-05-19 07:42 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +A shared instance of the following kube-prometheus component can be configured:
Probably worth it to add more detailed documentation (how-to or explanation) giving details on how "multi-instance" works for this component.

2022-05-19 07:42 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +
```suggestion

NOTE: The prometheus-operator deployed by this component will only reconcile resources in these namespaces.
```

Feel free to ignore this suggestion if it's not correct.

2022-05-19 07:42 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +This components addons can be found in the https://github.com/projectsyn/component-syn-kube-prometheus/tree/master/component/addons[`component/addons` folder].
```suggestion
Addons provided by this component can be found in the https://github.com/projectsyn/component-syn-kube-prometheus/tree/master/component/addons[`component/addons` folder].
```

2022-05-19 07:42 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Every deployable component can be configured by it's corresponding key.
```suggestion
Every deployable component can be configured in its corresponding key.
```

2022-05-19 07:42 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Default ruleLabels for all components.
```suggestion
Default alert rule labels for all components.
```

2022-05-19 07:52 UTC, glrf approved these changes
LGTM overall, just a few nitpicks. Feel free to ignore them

2022-05-19 07:52 UTC, glrf commented on component/main.jsonnet
> +);
I think this could be written a bit easier with `com.generateResources`

2022-05-19 07:52 UTC, glrf commented on component/main.jsonnet
> +  {} +
```suggestion
```

2022-05-19 08:11 UTC, bastjan commented on component/addons/nodeexporter-remove-mountpropagation.libsonnet
> +// This addons removes the mountPropagation field from the node-exporter host mounts.
@TheBigLee What is this used for? I just copied this part around and I'm not sure if it worked before.

Golden says it did not work:

https://github.com/projectsyn/component-syn-kube-prometheus/blob/484df9468ab5d1e6f423f0c88ad60a73188e0d8e/tests/golden/kubernetes_1.21/kubernetes_1.21/kubernetes_1.21/60_node-exporter-daemonset.yaml#L46

2022-05-19 08:12 UTC, bastjan commented on component/main.jsonnet
> +);
TIL

2022-05-19 08:25 UTC, bastjan commented on component/main.jsonnet
> +);
`com.generateResources` would mean the metadata key has to be added to the params which does not make as much sense for nammespaces. I'll leave as is. Makes perfect sense for secrets and co though.

2022-05-19 08:27 UTC, merged